---

name: Ansible Lint

on:
  push: {}
  pull_request: {}

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    name: ansible-lint

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Lint Ansible Playbooks
        uses: ansible/ansible-lint-action@master
        with:
          targets: "ansible/playbooks/*.yml"
